<?php namespace Monolith\DependencyInjection;

use Psr\Container\NotFoundExceptionInterface;

final class CanNotReflectivelyResolveTargetWithConstructorPrimitives extends DependencyInjectionException implements NotFoundExceptionInterface {}